# pyproject.toml
[tool.black]
# maximum line length
line-length = 88

# target Python versions (optional; e.g. py37, py38, py39)
target-version = ["py38"]

# don't normalize string quotes
skip-string-normalization = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-v",
    "--tb=short",
    "--strict-markers",
]
markers = [
    "unit: Unit tests for individual components",
    "integration: Integration tests for end-to-end workflows", 
    "debug: Debug utilities and temporary tools",
    "asyncio: Async test functions",
]