openapi: 3.1.0
info:
  title: idea-guy Function API
  version: "1.0.0"
  description: |
    Azure Function App that maintains a Google Spreadsheet of ideas
    and rates them on a variety of criteria.

servers:
  - url: https://idea-guy-func.azurewebsites.net
    description: Your deployed Function App

components:
  schemas: {}

  securitySchemes:
    azureFunctionKey:
      type: apiKey
      in: header
      name: x-functions-key
      description: |
        Your Azure Function host- or function-specific key.  
        Sent as the HTTP header `x-functions-key: YOUR_KEY`.

# apply this scheme to all operations by default
security:
  - azureFunctionKey: []

paths:
  /api/read-sheet:
    post:
      operationId: getIdeaSheetData
      summary: Returns the ideas data
      description: Returns the ideas data without any input parameters.
      responses:
        "200":
          description: Successful fetch of sheet data
          content:
            application/json:
              schema:
                type: object
                properties:
                  sheet_data:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: object
                        properties:
                          Description of Idea:
                            type: string
                          Notes:
                            type: string
                          Rating:
                            type: string
                        required:
                          - Description of Idea
                          - Notes
                          - Rating
              examples:
                sample:
                  summary: Example response
                  value:
                    sheet_data:
                      Ideas:
                        - Description of Idea: "test"
                          Notes: "- test notes"
                          Rating: "3"
        "500":
          description: Error processing request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                failure:
                  summary: Sample error
                  value:
                    error: "Invalid credentials or spreadsheet ID"
