openapi: 3.1.0
info:
  title: Joey Bot - Universal AI Agent Platform  
  version: "2.2.0"
  description: Idea Guy, rates business ideas.

servers:
  - url: https://idea-guy-func.azurewebsites.net
    description: Deployed Function App

components:
  schemas:
    UserInput:
      type: object
      required:
        - "Idea_Overview"
        - "Deliverable"
        - "Motivation"
      properties:
        "Idea_Overview":
          type: string
          description: Overview of the business idea
          example: "AI-powered meal planning app with personalized nutrition"
        "Deliverable":
          type: string
          description: What will be delivered
          example: "Mobile app with AI nutritionist and recipe database"
        "Motivation":
          type: string
          description: Motivation behind the idea
          example: "Help people achieve wellness goals through personalized nutrition"

  securitySchemes:
    azureFunctionKey:
      type: apiKey
      in: header
      name: x-functions-key

security:
  - azureFunctionKey: []

paths:
  /api/get_instructions:
    get:
      operationId: getInstructions
      summary: Get ChatGPT bot instructions
      description: Returns workflow instructions for the ChatGPT bot
      security: []
      responses:
        "200":
          description: Instructions retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  instructions:
                    type: string
                    description: System instructions for the bot

  /api/get_pricepoints:
    get:
      operationId: getPricepoints
      summary: Get budget options for analysis
      description: Returns available budget tiers with pricing and features
      parameters:
        - name: agent
          in: query
          description: Agent type (optional, defaults to business_evaluation)
          required: false
          schema:
            type: string
            example: "business_evaluation"
      responses:
        "200":
          description: Budget options retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  agent_type:
                    type: string
                    example: "business_evaluation"
                  pricepoints:
                    type: array
                    items:
                      type: object
                      properties:
                        level:
                          type: string
                          example: "standard"
                        name:
                          type: string
                          example: "Triple-Call Analysis"
                        max_cost:
                          type: number
                          example: 3.00
                        estimated_cost:
                          type: number
                          example: 3.00
                        model:
                          type: string
                          example: "gpt-4o-mini"
                        description:
                          type: string
                          example: "3 coordinated calls with intelligent architecture planning and web search capabilities"
                        time_estimate:
                          type: string
                          example: "15-20 minutes"
                  message:
                    type: string
                    example: "Select a budget tier and call /api/execute_analysis"
                  next_endpoint:
                    type: string
                    example: "/api/execute_analysis"

  /api/execute_analysis:
    post:
      operationId: executeAnalysis
      summary: Execute business analysis
      description: Start VC-level business analysis with selected budget tier using intelligent multi-call architecture with web search and reasoning capabilities
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_input
                - budget_tier
              properties:
                user_input:
                  $ref: '#/components/schemas/UserInput'
                budget_tier:
                  type: string
                  enum: ["basic", "standard", "premium"]
                  description: Selected budget tier (basic=$1, standard=$3, premium=$5)
      responses:
        "200":
          description: Analysis started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                    description: Job ID for polling results
                    example: "job_abc123"
                  status:
                    type: string
                    example: "processing"
                  budget_tier:
                    type: string
                    example: "standard"
                  message:
                    type: string
                    example: "Analysis completed with standard tier. Results available via job_id"
                  next_endpoint:
                    type: string
                    example: "/api/summarize_idea?id=job_abc123"
                  research_calls_made:
                    type: integer
                    description: Number of research calls executed
                    example: 2
                  synthesis_calls_made:
                    type: integer
                    description: Number of synthesis calls executed
                    example: 1
                  timestamp:
                    type: string
                    description: ISO timestamp of completion
                    example: "2025-08-02T23:34:09.121Z"

  /api/summarize_idea:
    get:
      operationId: summarizeIdea
      summary: Get completed analysis results
      description: Retrieve completed analysis results using job_id from execute_analysis.
      parameters:
        - name: id
          in: query
          required: true
          description: Job ID returned from execute_analysis endpoint
          schema:
            type: string
            example: "job_abc123"
      responses:
        "200":
          description: Analysis results retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "completed"
                  job_id:
                    type: string
                    example: "resp_abc123def456"
                  agent_type:
                    type: string
                    description: Type of agent that performed the analysis
                    example: "business_evaluation"
                  timestamp:
                    type: string
                    description: When the analysis was completed
                    example: "2025-08-02T23:34:09.121Z"
                additionalProperties:
                  type: string
                  description: Dynamic output fields based on agent configuration
                example:
                  "Novelty_Rating": "7/10"
                  "Novelty_Rationale": "Solid differentiation with AI personalization and dietary restriction focus. Market research shows 32M Americans have food allergies, creating clear demand for specialized meal kit services."
                  "Feasibility_Rating": "8/10"
                  "Feasibility_Rationale": "Strong technical feasibility. AI algorithms for nutritional analysis and recipe generation are achievable with current ML frameworks."
                  "Impact_Rating": "8/10"
                  "Impact_Rationale": "Significant market opportunity in $15B dietary restriction segment."
                  "Overall_Rating": "7/10"
                  "Analysis_Summary": "Promising investment opportunity with strong market fundamentals and clear differentiation."
        "404":
          description: Analysis not found or incomplete
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "not_found"
                  message:
                    type: string
                    example: "Analysis not found for job_id or analysis incomplete. Please check job_id or wait for analysis to complete."
                  job_id:
                    type: string
                    example: "job_abc123"

  /api/read_sheet:
    get:
      operationId: readSheet
      summary: Read analysis data from spreadsheet
      description: Retrieve stored analysis results from Google Sheets
      parameters:
        - name: id
          in: query
          required: false
          description: Optional ID to filter results
          schema:
            type: string
      responses:
        "200":
          description: Sheet data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  sheet_data:
                    type: object
                    description: Spreadsheet data organized by worksheet