openapi: 3.1.0
info:
  title: idea-guy Function API
  version: "1.0.0"
  description: |
    Azure Function App that maintains a Google Spreadsheet of ideas
    and rates them on a variety of criteria.

servers:
  - url: https://idea-guy-func.azurewebsites.net
    description: Your deployed Function App

components:
  schemas:
    IdeaRequest:
      type: object
      required:
        - "Idea_Overview"
        - "Deliverable"
        - "Motivation"
      properties:
        "Idea_Overview":
          type: string
          description: A comprehensive overview of the business idea
          example: "A mobile app that helps people find and book local fitness classes"
        "Deliverable":
          type: string
          description: What will be delivered or created as part of this idea
          example: "A mobile application with booking system and payment integration"
        "Motivation":
          type: string
          description: The motivation behind pursuing this idea
          example: "To solve the problem of people struggling to find and book fitness classes in their area"
    
    IdeaResponse:
      type: object
      properties:
        message:
          type: string
          description: Success message
          example: "Idea added successfully"
        "Idea_Overview":
          type: string
          description: The original idea overview that was submitted
          example: "A mobile app that helps people find and book local fitness classes"
        "Deliverable":
          type: string
          description: The original deliverable that was submitted
          example: "A mobile application with booking system and payment integration"
        "Motivation":
          type: string
          description: The original motivation that was submitted
          example: "To solve the problem of people struggling to find and book fitness classes in their area"
        "Analysis_Summary":
          type: string
          description: Detailed analysis and summary of the idea
          example: "This is a promising idea with good market potential. The fitness industry is growing rapidly..."
        "Novelty_Rating":
          type: integer
          minimum: 1
          maximum: 10
          description: Rating of how novel/unique the idea is (1-10 scale)
          example: 7
        "Feasibility_Rating":
          type: integer
          minimum: 1
          maximum: 10
          description: Rating of how feasible the idea is to implement (1-10 scale)
          example: 8
        "Effort_Rating":
          type: integer
          minimum: 1
          maximum: 10
          description: Rating of the effort required to implement the idea (1-10 scale)
          example: 6
        "Impact_Rating":
          type: integer
          minimum: 1
          maximum: 10
          description: Rating of the potential impact of the idea (1-10 scale)
          example: 8
        "Risk_Rating":
          type: integer
          minimum: 1
          maximum: 10
          description: Rating of the risk level associated with the idea (1-10 scale)
          example: 5
        "Overall_Rating":
          type: integer
          minimum: 1
          maximum: 10
          description: Overall rating of the idea (1-10 scale)
          example: 7
        timestamp:
          type: string
          format: date-time
          description: ISO timestamp when the idea was added
          example: "2024-01-15T10:30:00.123456"
    
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Missing required fields in request body"

  securitySchemes:
    azureFunctionKey:
      type: apiKey
      in: header
      name: x-functions-key
      description: |
        Your Azure Function host- or function-specific key.  
        Sent as the HTTP header `x-functions-key: YOUR_KEY`.

# apply this scheme to all operations by default
security:
  - azureFunctionKey: []

paths:
  /api/add_idea:
    post:
      operationId: addIdea
      summary: Add and analyze a new business idea
      description: |
        Accepts a business idea with three required fields (Idea_Overview, Deliverable, Motivation),
        uses OpenAI's GPT-4o model to rate it on multiple criteria (1-10 scale) 
        and provide detailed analysis, then stores the results in the Google Spreadsheet.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdeaRequest'
            examples:
              sample:
                summary: Sample idea submission
                value:
                  "Idea_Overview": "A subscription service for personalized meal planning with AI-generated recipes"
                  "Deliverable": "A web and mobile app with AI recipe generation and meal planning features"
                  "Motivation": "To help people eat healthier by providing personalized meal plans and recipes"
      responses:
        "200":
          description: Idea successfully added and analyzed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdeaResponse'
              examples:
                success:
                  summary: Successful idea addition
                  value:
                    message: "Idea added successfully"
                    "Idea_Overview": "A subscription service for personalized meal planning with AI-generated recipes"
                    "Deliverable": "A web and mobile app with AI recipe generation and meal planning features"
                    "Motivation": "To help people eat healthier by providing personalized meal plans and recipes"
                    "Analysis_Summary": "This is a strong concept with clear market demand. The AI component adds significant value..."
                    "Novelty_Rating": 7
                    "Feasibility_Rating": 8
                    "Effort_Rating": 6
                    "Impact_Rating": 8
                    "Risk_Rating": 5
                    "Overall_Rating": 7
                    timestamp: "2024-01-15T10:30:00.123456"
        "400":
          description: Bad request - missing or invalid fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                missing_fields:
                  summary: Missing required fields
                  value:
                    error: "Expected ['Idea_Overview', 'Deliverable', 'Motivation'], got ['idea']"
                empty_field:
                  summary: Empty field
                  value:
                    error: "Idea_Overview cannot be empty"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                analysis_failed:
                  summary: Analysis failed
                  value:
                    error: "Analysis failed, empty fields: Analysis_Summary, Novelty_Rating"
                server_error:
                  summary: Server error
                  value:
                    error: "Failed to add idea to spreadsheet"

  /api/read_sheet:
    get:
      operationId: getIdeaSheetData
      summary: Returns the ideas data from Google Sheets
      description: Returns all data from the Google Sheets spreadsheet containing the analyzed ideas.
      responses:
        "200":
          description: Successful fetch of sheet data
          content:
            application/json:
              schema:
                type: object
                properties:
                  sheet_data:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: object
                        additionalProperties:
                          type: string
                        description: Dynamic object with column headers as keys and cell values as strings
              examples:
                sample:
                  summary: Example response
                  value:
                    sheet_data:
                      Sheet1:
                        - Time: "2024-01-15 10:30:00"
                          "Idea_Overview": "A mobile app for fitness class booking"
                          "Deliverable": "Mobile application with booking system"
                          "Motivation": "Solve fitness class discovery problem"
                          "Analysis_Summary": "Promising idea with good market potential"
                          "Novelty_Rating": "7"
                          "Feasibility_Rating": "8"
                          "Effort_Rating": "6"
                          "Impact_Rating": "8"
                          "Risk_Rating": "5"
                          "Overall_Rating": "7"
        "500":
          description: Error processing request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                failure:
                  summary: Sample error
                  value:
                    error: "Invalid credentials or spreadsheet ID"

  /api/get_instructions:
    get:
      operationId: getInstructions
      summary: Get system instructions for the GPT bot
      description: |
        Returns the system message/instructions that define the role and behavior
        of the GPT bot for analyzing business ideas. This endpoint is used to
        understand what information the bot needs to collect from users.
      security: []  # No authentication required (anonymous access)
      responses:
        "200":
          description: Instructions retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  instructions:
                    type: string
                    description: The system message/instructions for the GPT bot
                    example: "You are an expert business analyst who evaluates startup ideas and business opportunities."
              examples:
                success:
                  summary: Successful instructions retrieval
                  value:
                    instructions: "You are an expert business analyst who evaluates startup ideas and business opportunities. Your job is to ask the user for and confirm the values of the following pieces of information: Idea_Overview, Deliverable, Motivation"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                server_error:
                  summary: Server error
                  value:
                    error: "Failed to retrieve instructions"
